In [1]:
import numpy as np

In [4]:
s = np.arange(10)
s.shape

(10,)

In [15]:
a1 = np.zeros((3,2),'int')
print(a1)

[[0 0]
 [0 0]
 [0 0]]


In [20]:
a1 = np.arange(10)
print('a1:\n', a1)

a2 = a1.reshape(5,2)
print('a2:\n', a2)

a1:
 [0 1 2 3 4 5 6 7 8 9]
a2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
a1 = np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
a2 = a1.reshape(-1,5)
print(a2)
print(a2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [24]:
a3 = a1.reshape(5,-1)
print(a3)
print(a3.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [25]:
a1 = np.arange(8)
a3 = a1.reshape(2,2,2)

In [26]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [27]:
print(a3.tolist())

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [29]:
a3 = a3.reshape(-1,1)
print(a3)
print(a3.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [30]:
a2 = a1.reshape(-1,1)
print(a1)
print(a2)

[0 1 2 3 4 5 6 7]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [31]:
a1 = np.arange(1,10)

In [32]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
value = a1[2]

In [34]:
value

3

In [35]:
print(type(a1[2]))

<class 'numpy.int32'>


In [37]:
a1[-3]

7

In [38]:
a1[0] = 9
a1[8] = 0

In [39]:
a1

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [40]:
a1

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [41]:
a1[0] = 0
a1[8] = 9
a1

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a1 = np.arange(1,10)

In [46]:
a2 = a1.reshape(3,-1)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a2[0,0]

1

In [48]:
a2[0,1]

2

In [50]:
a2[2,2]

9

In [51]:
a1 = np.arange(1,10)

In [52]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1[0:3]

array([1, 2, 3])

In [54]:
print(type(a1[0:3]))

<class 'numpy.ndarray'>


In [55]:
a1 = np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a1[:3]

array([1, 2, 3])

In [57]:
a1[3:]

array([4, 5, 6, 7, 8, 9])

In [58]:
a1[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1 = np.arange(1,5)
a1

array([1, 2, 3, 4])

In [66]:
a2 = a1.reshape(2,2)
a2

array([[1, 2],
       [3, 4]])

In [69]:
a1 = np.arange(1, 10)
a2 = a1.reshape(3,3)

In [70]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
a2[0:2, 1:2]

array([[2],
       [5]])

In [76]:
a1 = np.arange(1,10)
a2 = a1.reshape(3,3)

In [77]:
a2.shape

(3, 3)

In [78]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
a2[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

정렬 행렬의 인덱스 반환

In [91]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [92]:
org_array = np.array([ 3, 1, 9, 5]) #np.array()로 1차원 ndarray 생성
sort_indices_desc = np.argsort(org_array)[::-1] #np.argsort()로 원본행렬 원소에 대한 인덱스 추출 후 내림차순으로 변환
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [93]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])  #1차원 ndarray 생성
score_array= np.array([78, 95, 84, 98, 88]) #1차원 ndarray 생성

sort_indices_asc = np.argsort(score_array) #np.argsort()로 성적 오름차순 정렬
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc]) #name_array에 fancy-indexing(리스트 형태로 인덱스 집합을 지정) 적용

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

행렬내적

In [95]:
A = np.array([[1, 2, 3],  #2차원 ndarray 생성
              [4, 5, 6]])
B = np.array([[7, 8],      #2차원 ndarray 생성
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B) #np.dot()을 이용해 A,B 두 matrix의 내적값 계산
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


전치행렬

In [98]:
A = np.array([[1, 2],  #2차원 ndarray 생성
              [3, 4]])
transpose_mat = np.transpose(A) #np.tranpose()를 이용해 A matrix의 전치행렬 구하기
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


In [103]:
a1 = np.arange(1,10)
a2 = a1[a1 > 5]
a1
a2
a1>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [106]:
a = np.array([False, True, False, True])
print(a1)
print(a1[a])

[1 2 3 4 5 6 7 8 9]


IndexError: boolean index did not match indexed array along dimension 0; dimension is 9 but corresponding boolean dimension is 4

In [114]:
a1 = np.arange(1,4)
a = a1[[False, True, True]]
a

array([2, 3])

In [117]:
indexes = np.array([5,6,7,8])
a1 = np.arange(1,10)
a1[[5,6,7]]

array([6, 7, 8])

In [118]:
a = [1,2,3]
type(a)

list

In [120]:
[a>1]

TypeError: '>' not supported between instances of 'list' and 'int'

In [123]:
a = np.arange(1,4)
a
a[a>1]

array([2, 3])

In [124]:
a = np.array([3,1,9,5])
a

array([3, 1, 9, 5])

In [126]:
np.sort(a)
print(a)

[3 1 9 5]


In [128]:
a.sort()
a

array([1, 3, 5, 9])

In [132]:
a = np.array([3,4,7,2])
b = np.sort(a)[::-1]
print(b)
print()

[7 4 3 2]
[3 4 7 2]


In [133]:
a2 = np.array([[8,12],
              [7,1]])

In [142]:
a2 = np.array([1,3,6,2])
np.sort(a2)

array([1, 2, 3, 6])

In [138]:
np.sort(a2, axis=0)

array([[ 7,  1],
       [ 8, 12]])

In [139]:
np.sort(a2, axis=1)

array([[ 8, 12],
       [ 1,  7]])

In [143]:
a = np.array([3,1,9,5])
b = np.argsort(a)
print(type(b))

<class 'numpy.ndarray'>


In [146]:
name = np.array(['a','b','c','d'])
score = np.array([3,4,2,1])

print(name[np.argsort(score)])

['d' 'c' 'a' 'b']


In [150]:
a = np.array([[1,2,3],
             [4,5,6]])

b = np.array([[7,8],
             [9,10],
             [11,12]])

b.shape

(3, 2)

In [151]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [153]:
a = np.array([[1,2],
             [3,4]])

a.shape

(2, 2)

In [155]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

## Pandas 시작- 파일을 DataFrame 로딩, 기본 API

In [157]:
import pandas as pd

In [169]:
titanic_df = pd.read_csv("C:/Users/kyw97/Downloads/titanic_train.csv")
print('titanic 변수 type: ', type(titanic_df))
titanic_df

titanic 변수 type:  <class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [172]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [174]:
print('DataFrame 크기: ', titanic_df.shape)

DataFrame 크기:  (891, 12)


In [177]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [178]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [188]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [190]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [191]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [195]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64


In [209]:
print('titanic_df 데이터 건수:', titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일.
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
S    644
C    168
Q     77
Name: Embarked, dtype: int64
S      644
C      168
Q       77
NaN      2
Name: Embarked, dtype: int64


# DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

- 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기

In [217]:
import numpy as np

col_name1=['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape:', array1.shape )
# 리스트를 이용해 DataFrame 생성.
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
# 넘파이 ndarray를 이용해 DataFrame 생성.
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [218]:
# 3개의 칼럼명이 필요함.
col_name2=['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape )
df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [228]:
# 딕셔너리의 Key는 컬럼명으로 매핑, 각 value는 칼럼의 데이터로 맵핑됨.
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]} 

#DataFrame()에 인자로 딕셔너리를 할당해 데이터프레임 생성
df_dict = pd.DataFrame(dict) 
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


- DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

In [235]:
# DataFrame 객체의 values를 이용해 dataframe을 ndarray로 변환
array3 = df_dict.values

#array3는 ndarray타입으로 변환되었고, ndarray의 크기는 (2,3)
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [242]:
# 객체의 values를 이용해 데이터프레임->ndarray로 변환후, tolist()를 통해 ndarray->리스트로 변환
# DataFrame -> ndarray -> list
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

# 객체의 to_dict를 통해 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [253]:
titanic_df['Age_0'] = 0

In [259]:
titanic_df['Age_0'].value_counts()

0    891
Name: Age_0, dtype: int64

In [261]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [269]:
a = np.zeros((2,3))

In [273]:
titanic_df['Age_by_10'] = titanic_df['Age']*10

In [279]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0        0         A/5 21171   7.2500   NaN        S      0      220.0   
1        0          PC 17599  71.2833   C85        C      0      380.0   
2        0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   
3        0            113803  53.1000  C123        S      0      350.0   
4        0            373450   8.0500   NaN        S      0      350.0   
..     ...               ...      ...   ...      ...    ...        ...   
886      0            211536  13.0000   NaN        S      0      270.0   
887      0            112053  30.0000   B42        S      0      190.0   
888      2        W./C. 6607  23.4500   NaN        S      0        NaN   
889      0            111369  30.0000  C148        C      0      260.0   
890      0            370376   7.7500   NaN        Q      0      320.0   

     Family_No  
0            2  
1            2  
2            1  
3            2  
4            1  
..         ...  
886          1  
887          1  
888          4  
889          1  
890          1  

[891 rows x 15 columns]

In [275]:
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1

In [278]:
titanic_df[['Family_No']].head()

Family_No
0          2
1          2
2          1
3          2
4          1

In [280]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0        0         A/5 21171   7.2500   NaN        S      0      320.0   
1        0          PC 17599  71.2833   C85        C      0      480.0   
2        0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   
3        0            113803  53.1000  C123        S      0      450.0   
4        0            373450   8.0500   NaN        S      0      450.0   
..     ...               ...      ...   ...      ...    ...        ...   
886      0            211536  13.0000   NaN        S      0      370.0   
887      0            112053  30.0000   B42        S      0      290.0   
888      2        W./C. 6607  23.4500   NaN        S      0        NaN   
889      0            111369  30.0000  C148        C      0      360.0   
890      0            370376   7.7500   NaN        Q      0      420.0   

     Family_No  
0            2  
1            2  
2            1  
3            2  
4            1  
..         ...  
886          1  
887          1  
888          4  
889          1  
890          1  

[891 rows x 15 columns]