# 1.3 Numpy 넘파이

### Numpy ndarray 개요

In [1]:
#alias로 넘파이 모듈 임포트
import numpy as np

In [2]:
#np.array()로 numpy의 ndarray 생성, 인자에 리스트값을 입력받아 ndarray로 변환

#1차원 ndarray
array1 = np.array([1,2,3])                   
print('array1 type:',type(array1))           #생성한 ndarray의 타입 확인
print('array1 array 형태:',array1.shape)     #shape 변수로 ndarray의 크기 확인

#2차원 ndarray
#2차원 ndarray는 대괄호 2개로 행과 열 구분
array2 = np.array([[1,2,3],                
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
#ndarray의 ndim변수로 ndarray의 차원을 알 수 있음.

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
#리스트 생성 후 타입확인
list1 = [1,2,3]
print(type(list1))

#np.array()메서드 인자에 리스트를 입력받아 리스트 -> ndarray로 변환
array1 = np.array(list1)
print(type(array1))            #array1의 타입은 ndarray
print(array1, array1.dtype)    #ndarray 안 데이터들의 타입확인은 dtype 변수로 할 수 있음. 

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
#ndarray에는 같은 타입의 데이터들만 저장가능.

#정수형과 문자열로 이루어진 리스트 생성
list2 = [1, 2, 'test']
#np.array()로 리스트 -> ndarray 변환
array2 = np.array(list2)       
print(array2, array2.dtype) #ndarray 안 정수 데이터들은 더 큰 문자열 타입으로 형변환되어 문자열로 변환됨.

list3 = [1, 2, 3.0]
array3 = np.array(list3)    #ndarray 안 정수 데이터들은 더 큰 float 타입으로 형변환되어 flaot형으로 변환됨.
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
#ndarray 안 데이터타입은 astype() 메서드로 변경가능
#astype() 인자로 원하는 타입을 문자열로 입력.
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')    #생성한 ndarray를 'float64'타입으로 변경.
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')      #생성한 ndarray를 'int32'타입으로 변경.
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])     #생성한 ndarray를 'int32'타입으로 변경.
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [7]:
#np.arange()에 인자로 정수를 입력해 연속된 정수형 데이터 생성 / 0 ~ 인자값 -1까지의 순차적으로 저장됨.
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
#np.zeros()에 인자로 원하는 ndarray의 크기를 튜플형태로 넣어 0으로만 이루어진 ndarray 생성
#원하는 데이터타입도 dtype으로 지정 가능.
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))         #dtype을 지정하지 않으면, 기본형인 float64로 생성됨.
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [10]:
#ndarray의 크기를 reshape()메서드로 변경할 수 있음.
array1 = np.arange(10)
print('array1:\n', array1)

#1차원 ndarray -> (2,5)의 2차원 ndarray로 변경
array2 = array1.reshape(2,5)
print('array2:\n',array2)

#1차원 ndarray -> (5,2)의 2차원 ndarray로 변경
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1.reshape(4,3)     #원본 ndarray의 크기는 (10,)이므로 (4,3)의 2차원 ndarray를 만들 수 없음.

ValueError: cannot reshape array of size 10 into shape (4,3)

In [12]:
array1 = np.arange(10)
print(array1)

#reshape()메서드 인자에 -1을 입력하면 다른 행or열 값에 따라 자동으로 ndarray 크기를 변경해줌.
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [13]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)    #생성한 ndarray의 크기가 (10,)이므로 -1을 넣어도 2차원의 데이터로 자동변환 불가.

ValueError: cannot reshape array of size 10 into shape (4)

In [20]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))         #생성한 1차원 데이터를 (2,2,2)형태의 3차원 데이터로 변환
print('array3d:\n',array3d.tolist())      #tolist()메서드로 ndarray -> list 로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### indexing

* 단일값 추출

In [21]:
# 1에서부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [22]:
#ndarray의 단일값 추출시 []에 -1 인자를 입력하면 맨 뒤의 데이터, -2를 입력하면 맨뒤에서 두번째 데이터가 추출됨.
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [23]:
#ndarray의 데이터를 변경은 변경할 인덱스를 입력 후 값을 할당하면 됨. 
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [24]:
array1d = np.arange(start=1, stop=10)     #1~9까지의 연속된 정수형 데이터로 이루어진 1차원 ndarray 생성.
array2d = array1d.reshape(3,3)            #reshape()메서드를 통해 (3,3)의 2차원 ndarray로 변환.
print(array2d)

#2차원 ndarray의 단일값 추출은 []에 인자로 행,열의 인덱스를 입력해주면 됨.
print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* Slicing

In [25]:
#슬라이싱은 [] 인자에 시작인덱스:종료인덱스 입력 / 시작인덱스 ~ 종료인덱스-1 까지의 ndarray가 반환됨.
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [27]:
#[]인자로 인덱스값을 입력하지 않을 경우, 처음 or 끝으로 인식.
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]     #인덱스 0~2까지의 ndarray 반환
print(array4)

array5 = array1[3:]     #인덱스 3~끝까지 ndarray 반환
print(array5)

array6 = array1[:]      #인덱스 처음부터 끝까지의 ndarray 반환
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [28]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)       #2차원의 (3,3)크기의 ndarray 생성
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])    #행 [0,1] 열 [0,1]의 ndarray 생성
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])    #행 [1,2] 열 [0,1,2]의 ndarray 생성
print('array2d[1:3, :] \n', array2d[1:3, :])        #행 [1,2] 전체 열의 ndarray 생성
print('array2d[:, :] \n', array2d[:, :])            #전체 ndarray 반환
print('array2d[:2, 1:] \n', array2d[:2, 1:])        #행 [0,1] 1번째 열부터 끝까지 ndarray 생성
print('array2d[:2, 0] \n', array2d[:2, 0])          #행 [0.1] 0번째 열의 ndarray 반환

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [29]:
print(array2d[0])     #2차원 ndarray의 0번째 행 출력
print(array2d[1])     #2차원 ndarray의 1번째 행 출력
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* fancy indexing

In [30]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

#팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치에 해당하는 ndarray를 반환해주는 것.
array3 = array2d[[0,1], 2]     #행[0,1] 2번째 열의 ndarray 반환
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]   #행[0,1] 열[0,1]의 ndarray 반환
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]        #행 [0,1] 전체열의 ndarray 반환
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [33]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [35]:
#array1d > 5처럼 ndarray[] 안에 조건식을 할당하면, 조건에 맞게 True/False로 변환된 ndarray가 반환됨.
#True/False로 이루어진 ndarray를 다시 원본 ndarray[]에 인자로 입력하면, 조건에 맞는 ndarray가 반환됨.
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [36]:
#위 조건필터링 불린인덱싱은 True/False로 이루어진 ndarray를 할당한 아래와 같음.
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [38]:
#인덱스집합을 직접 만들어 대입한 것과 동일.
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [40]:
#ndarray 행렬의 정렬은 ndarray.sort()와 np.sort(ndarray)가 있음.

#ndarray.sort()는 원본 행렬을 정렬하여 바꾸되, 반환값이 없음.
#np.sort(ndarray)는 정렬한 행렬을 반환하되, 원본 행렬은 유지.
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [42]:
#np.sort(ndarray)는 기본적으로 오름차순으로 정렬된 ndarray를 반환
#내림차순으로 출력 시에는 [::-1]을 통해 맨 뒤 값부터 출력 
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [43]:
#2차원 이상의 ndarray의 경우에는 axis=0 or axis=1을 통해 row나 column 상 정렬가능
array2d = np.array([[8, 12], 
                   [7, 1 ]])

#axis = 0이면 행을 의미
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

#axis = 1은 열을 의미
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [45]:
#np.argsort() : 정렬된 행렬의 원본 행렬 인덱스를 반환해주는 메서드
#원본행렬의 인덱스를 ndarray형태로 반환

org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [46]:
#내림차순으로 정렬한 원본행렬의 인덱스를 구하고 싶을 경우, np.argsort() 반환값을 [::-1]로 뒤에서부터 출력
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [47]:
#ndarray는 그 값이 뜻하는 메타데이터를 별도의 ndarray로 가져야만 한다.
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])   #별도의 name_array라는 ndarray 생성
score_array= np.array([78, 95, 84, 98, 88])

#score_array를 np.argsort()로 정렬 후 원본행렬의 인덱스 반환, 반환된 인덱스로 학생의 이름 출력.
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [48]:
#행렬내적은 행렬곱, np.dot()을 통해 간단히 내적가능.

A = np.array([[1, 2, 3],      #(2,3)크기의 ndarray 생성
              [4, 5, 6]])
B = np.array([[7, 8],         #(3,2)크기의 ndarray 생성
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [49]:
#전치행렬은 원본 행렬의 행과 열 위치를 교환한 행렬
#np.transpose()를 통해 전치행렬을 간단히 구할 수 있음.
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


# 1.4 Pandas 판다스

### Pandas 시작- 파일을 DataFrame 로딩, 기본 API

In [147]:
#alias로 판다스 임포트
import pandas as pd

In [148]:
#read_csv()메서드로 csv파일을 바로 데이터프레임 객체로 변환 가능
titanic_df = pd.read_csv("C:/Users/kyw97/Downloads/titanic_train.csv")
print('titanic 변수 type:',type(titanic_df))    #데이터프레임의 타입 확인
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0              1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1              2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2              3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3              4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..           ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [149]:
#데이터프레임의 크기는 shape변수로 확인 가능
print('DataFrame 크기: ', titanic_df.shape)

DataFrame 크기:  (891, 12)


In [150]:
#info()로 데이터프레임의 정보 확인 가능.
#전체 row와 column수
#칼럼명
#non-null인 데이터의 개수
#데이터의 타입
#전체 칼럽들의 데이터 타입 요약

titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [151]:
#describe()로 숫자형데이터들에 대한 칼럼별 데이터 분포도 확인 가능.
#count / mean / std / min/ 25% / 50% / 75% / max

titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [152]:
#데이터프레임의 []안에 칼럼명을 입력하면 series형태로 그 칼럼의 데이터세트 반환.
#value_counts()는 유형별로 데이터들의 개수를 알 수 있음.

value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

#개수 앞 데이터들은 인덱스인데, 이 경우 Pclass가 고유하므로 Pclass가 인덱스를 대체

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [153]:
titanic_pclass = titanic_df['Pclass']

#titanic_pclass의 타입은 series
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [154]:
#head()로 앞부터 5개의 데이터 나타내기
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [155]:
#Pclass 칼럼에서 value_counts()로 유형별 데이터 건수 확인
value_counts = titanic_df['Pclass'].value_counts()

#value_counts의 타입은 series
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64


In [156]:
#shape변수에서 0번째 인덱스는 행값
print('titanic_df 데이터 건수:', titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')

#value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일.
#value_counts()는 유형별 데이터의 개수를 셀 때 디폴트로 NULL값을 제외시킴.
print(titanic_df['Embarked'].value_counts())

#value_counts() 적용시 NULL값도 포함시키고 싶다면 value_counts()인자에 'dropna=False'
print(titanic_df['Embarked'].value_counts(dropna=False))

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
S    644
C    168
Q     77
Name: Embarked, dtype: int64
S      644
C      168
Q       77
NaN      2
Name: Embarked, dtype: int64


### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

* 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기

In [157]:
import numpy as np

col_name1=['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape:', array1.shape )

#리스트를 이용해 DataFrame 생성.
#pd.DataFrame()메서드 안에 데이터 입력
#데이터프레임은 컬럼이 존재하므로 컬럼명을 columns 파라미터에 따로 지정해주어야함.
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

# 넘파이 ndarray를 이용해 DataFrame 생성.
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [158]:
# (2,3)크기의 ndarray이므로 3개의 칼럼명이 필요함.
col_name2=['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape )

#데이터프레임은 칼럼이 있기 때문에 따로 columns 파라미터에 칼럼명 지정해야함.
#리스트 -> 데이터프레임
df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
#ndarray -> 데이터프레임
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [159]:
#딕셔너리 -> 데이터프레임
# Key는 컬럼명으로 매핑, Value는 컬럼 안 데이터들로 맵핑됨.
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


* DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

In [160]:
#데이터프레임 -> ndarray
#values변수를 이용해 데이터프레임에서 컬럼 안 데이터들만 추출

#values변수를 사용하면 데이터들이 ndarray형태로 반환됨.
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [161]:
#데이터프레임 -> 리스트
#(데이터프레임 -> ndarray -> (tolist()를 통해 리스트)
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

#데이터프레임 -> 딕셔너리
#to_dict()로 딕셔너리로 변환, 인자에 'list'를 입력하면 딕셔너리의 value가 리스트형으로 반환됨.
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


### DataFrame의 컬럼 데이터 셋 Access

In [162]:
#데이터프레임 뒤 []연산자에 'Age_0'이라는 새로운 칼럼명을 넣어 새 칼럼을 만들고, 상수 0을 할당해 모든 값을 0으로 저장.
titanic_df['Age_0']=0
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

In [163]:
#새로운 칼럼을 생성하고, 기존 데이터들을 가공해 데이터를 저장.
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1

In [164]:
#기존 칼럼 데이터들을 연산 후 다시 할당하여 값들을 업데이트.
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

### DataFrame 데이터 삭제

In [165]:
#데이터프레임에서 데이터 삭제는 drop()메서드를 사용.
#drop()의 원형: drop(labels = None, axis = 0, inplace = False)

#데이터프레임에서 'Age_0'이라는 칼럼을 axis=1 방향으로 drop
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      360.0          1

In [166]:
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

In [167]:
#drop() 인자에 inplace=True를 하면, 원본 데이터프레임의 값이 변경, 반환값은 없음.
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print(' inplace=True 로 drop 후 반환된 값:',drop_result)
titanic_df.head(3)

 inplace=True 로 drop 후 반환된 값: None


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [168]:
pd.set_option('display.width', 1000)
#데이터프레임의 최대로 보일 수 있는 컬럼의 너비를 15로 설정
pd.set_option('display.max_colwidth', 15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

#행을 drop하고 싶을 경우, 인덱스 집합 설정 후 axis=0
titanic_df.drop([0,1,2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


### Index 객체

In [174]:
#원본 파일 재로딩 
titanic_df = pd.read_csv("C:/Users/kyw97/Downloads/titanic_train.csv")

#index 변수로 인덱스 객체 추출.
indexes = titanic_df.index
print(indexes)

#Index 객체에서 실제 값을 보기 위해 values변수로 ndarrray로 변환 
print('Index 객체 array값:\n',indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232

In [175]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [177]:
#인덱스는 고유성을 가지고 데이터들을 식별할 수 있어야 하기 때문에 변경할 수 없음.
indexes[0] = 5

TypeError: Index does not support mutable operations

In [180]:
#인덱스는 오직 식별용, series 객체에 연산을 적용할 때 인덱스는 제외됨.
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3:\n',(series_fair + 3).head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [181]:
#reset_index()는 연속 숫자형의 새로운 인덱스를 할당, 기존 인덱스는 바로 오른쪽에 새로운 칼럼으로 추가됨.
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [188]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:',type(value_counts))

#reset_index로 새로운 인덱스 할당, 기존 인덱스였던 Pclass는 바로 오른쪽에 칼럼으로 추가됨.
new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:',type(new_value_counts))

### before reset_index ###
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>


### 데이터 셀렉션 및 필터링

* DataFrame의 [ ] 연산자

In [191]:
print('단일 컬럼 데이터 추출:\n', titanic_df[ 'Pclass' ].head(3))

#데이터프레임 뒤에 오는 [] 연산자 내에는 *칼럼명*만 작성해야함.
#여러개의 칼럼을 가져오고 싶을 경우, 데이터프레임[] 연산자 내부에 리스트로 칼럼명을 작성
print('\n여러 컬럼들의 데이터 추출:\n', titanic_df[ ['Survived', 'Pclass'] ].head(3))

#데이터프레임[] 안에 숫자를 입력할 경우 오류발생.
print('[ ] 안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])

단일 컬럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 컬럼들의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3


KeyError: 0

In [195]:
#인덱스 형태로 변환가능한 표현식은 적용가능.
titanic_df[0:2]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [196]:
#불린인덱싱 표현 가능.
titanic_df[titanic_df['Pclass'] == 3].head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

* DataFrame iloc[ ] 연산자

In [209]:
#데이터프레임의 인덱싱 방식에는 위치기반 인덱싱(iloc[]) / 명칭기반 인덱싱(loc[]이 있음.
data = {'Name': ['Chulmin', 'Eunkyung','Jinwoong','Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
       }

#데이터프레임 생성 시 index 인자에 값을 넣어 원하는 인덱스로 지정가능.
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [210]:
#0번째 행, 0번째 열의 데이터값 가져오기
data_df.iloc[0, 0]

'Chulmin'

In [216]:
#iloc[]는 위치기반 인덱싱이므로 정수가 아닌 다른 값을 넣으면 오류가 발생
data_df.iloc[0, 'Name']
data_df.iloc['one', 0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [217]:
#iloc[]는 열 위치에 -1을 입력하여 데이터프레임의 가장 마지막 칼럼을 가져오는 데 자주 사용함.

print("\n 맨 마지막 칼럼 데이터 [:, -1] \n", data_df.iloc[:, -1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] \n", data_df.iloc[: , :-1])


 맨 마지막 칼럼 데이터 [:, -1] 
 one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object

 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] 
            Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015


* DataFrame loc[ ] 연산자

In [221]:
#loc[]는 명칭기반 인덱싱, 행 위치에는 인덱스값을, 열 위치에는 칼럼명을 입력함.
data_df.loc['one', 'Name']

'Chulmin'

In [223]:
#loc[]는 명칭기반 인덱싱이기 때문에 인덱스값인지 잘 확인해야함.
#이 경우 0이라는 인덱스는 존재하지 않기 때문에 오류 발생.
data_df.loc[0, 'Name']

KeyError: 0

In [224]:
#위치기반 인덱싱 loc[]는 숫자형이 아닐 확률이 높기 때문에 종료값-1이 아니라 종료값까지 데이터를 가져옴.
print('위치기반 iloc slicing\n', data_df.iloc[0:1, 0],'\n')
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name'])

위치기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object 

명칭기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object


* 불린 인덱싱

In [234]:
titanic_df = pd.read_csv("C:/Users/kyw97/Downloads/titanic_train.csv")

#불린 인덱싱은 [], loc[]에서 공통으로 지원함.
#데이터프레임 뒤 []에 조건식을 입력하면 자동으로 원하는 결과를 찾아줌.
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [237]:
#[] 이용
#전체 데이터프레임에서 리스트로 원하는 칼럼들만 추출하기
titanic_df[titanic_df['Age'] > 60][['Name','Age']].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [239]:
#loc[] 이용
#조건식을 행 위치에, 원하는 칼럼명 리스트를 열 위치에 입력.
titanic_df.loc[titanic_df['Age'] > 60, ['Name','Age']].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [241]:
#여러 개의 복합조건을 결합해 사용할 수 있음.
titanic_df[(titanic_df['Age'] > 60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [242]:
#복합조건을 개별조건으로 변수에 할당하고, 이 변수들을 결합해서 불린 인덱싱을 할 수도 있음.
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[ cond1 & cond2 & cond3]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

### 정렬, Aggregation함수, GroupBy 적용

* DataFrame, Series의 정렬 - sort_values()

In [243]:
#데이터프레임에서의 정렬은 sort_values()메서드를 이용.
#by 파라미터에 정렬을 원하는 칼럼명 입력
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [249]:
#여러 개의 칼럼을 정렬하고 싶을 경우 by 파라미터에 리스트로 칼럼명을 전달
#내림차순으로 정렬을 원할 경우 ascending = False로 지정(기본값은 ascending = True)
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

* Aggregation 함수 적용

In [257]:
#aggregation함수를 데이터프레임에 적용하면 모든 칼럼들에 함수가 적용이 됨.
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [258]:
#데이터프레임의 특정 칼럼들에만 aggregation 함수를 적용하고 싶다면, 특정 칼럼들 추출 후 함수 적용.
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

* groupby() 이용하기

In [259]:
#groupby()의 by 파라미터에 칼럼명을 입력하면 해당 칼럼으로 groupby되고, groupby객체가 반환됨.
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [260]:
#반환된 groupby객체에 count() 함수 적용.
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [261]:
#'Pclass'별로 groupby() 후 원하는 칼럼들만 추출해 count() 함수 적용.
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [270]:
#서로 다른 aggregation 함수를 적용하고 싶을 경우, 리스트로 묶어 agg()에 전달.
titanic_df.groupby('Pclass')['Age'].agg([max, min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [271]:
#서로 다른 칼럼들에 서로 다른 함수를 적용하고 싶을 경우, agg()메서드의 인자로 딕셔너리를 전달.
#'Age'에는 max함수, 'SibSp'에는 sum함수, 'Fare'에는 mean함수를 적용.

agg_format={'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### 결손 데이터 처리하기
* isna()로 결손 데이터 여부 확인

In [279]:
#결손데이터인지 여부를 확인하는 isna().
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False  False     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False  False     False

In [280]:
#True는 1, False는 0이므로 sum()을 적용해 NULL의 개수 확인.
titanic_df.isna( ).sum( )

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

* fillna( ) 로 Missing 데이터 대체하기

In [284]:
#NULL값을 대체하는 fillna()메서드
#대체할 값을 fillna()메서드에 인자로 입력.
#inplace = False로 반환값을 다시 받거나, inplace = True로 원본 데이터프레임을 변경.
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

In [285]:
#'Age_'칼럼을 'Age'의 평균값으로 채우기
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
#'Embarked'칼럼을 'S'값으로 채우기
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### apply lambda 식으로 데이터 가공

In [296]:
#def로 get_square() 함수 생성
def get_square(a):
    return a**2

print('3의 제곱은:',get_square(3))

3의 제곱은: 9


In [299]:
#lamda표현식을 사용할 경우 한 줄로 간단해짐.
lambda_square = lambda x : x ** 2
print('3의 제곱은:',lambda_square(3))

3의 제곱은: 9


In [306]:
#여러 개의 인자를 함수에 적용하고 싶을 경우 map()함수 사용
a=[1,2,3]
squares = map(lambda x : x**2, a)
#map객체를 list로 변환하여 값 알아보기
list(squares)

[1, 4, 9]

In [290]:
#다중 칼럼에서는 apply 사용.
titanic_df['Name_len']= titanic_df['Name'].apply(lambda x : len(x))
#titanic_df[['Name','Name_len']].head(3)

Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [316]:
#lambda함수의 if절의 경우 반환값은 항상 lambda식 : 뒤에 있어야함.
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else 'Adult' )
titanic_df[['Age','Child_Adult']].head(8)

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [324]:
#lambda식에서는 elif문이 없기 때문에, else 후 ()로 또 다른 조건식을 작성해야함.
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60 else 
                       
                                                                                  'Elderly'))
titanic_df['Age_cat'].value_counts()

Adult      786
Child       83
Elderly     22
Name: Age_cat, dtype: int64

In [325]:
#나이에 따라 세분화된 분류를 수행하는 함수 생성. 
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else : cat = 'Elderly'
    
    return cat

#위에서 생성한 get_category()를 lambda식의 리턴값으로 지정
#get_category(x)는 입력값으로 ‘Age’칼럼 안의 값들을 받아서 함수 적용 후 cat 반환.
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age','Age_cat']].head()

Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult